version: "3"

services:
  postgres_perinity:
    container_name: postgres_perinity
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pg_tasklist